### ISSUE TITLE
Format the values from the output tables to include $ and commas

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/us-marriage-incentive#21]
E.g. 
$2,000.13
![image](https://github.com/PolicyEngine/us-marriage-incentive/assets/110687043/05fab99a-47bb-425e-9246-2ca8ba783f6d)

Also in the penalty and bonus outputs:
![image](https://github.com/PolicyEngine/us-marriage-incentive/assets/110687043/d34e8a78-aab2-40b7-9753-06545dd7899a)

**Comment by MaxGhenis** [comment]
let's round to the $1
