### ISSUE TITLE
Reformat table

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/us-marriage-incentive#27]
1. Spell out the row labels: Net income, Benefits, Refundable tax credits, Taxes before refundable credits
2. Remove row numbers
3. Add net income row
4. Format numbers $x,xxx
5. Remove market income row (this never changes)

<img width="884" alt="image" src="https://github.com/PolicyEngine/us-marriage-incentive/assets/6076111/1a205ef3-8e24-4183-a919-c4f1518c5daf">

**Comment by PavelMakarchuk** [comment]
@emieelvire net income var in PE-us: `household_net_income`

4. was addressed in #25
