### ISSUE TITLE
Format Table: Swap Not Married and Married Columns & Add Delta in Percentage

### ISSUE THREAD

**Issue by emieelvire** [PolicyEngine/us-marriage-incentive#43]
<img width="811" alt="Screenshot 2024-03-17 at 8 04 18 PM" src="https://github.com/PolicyEngine/us-marriage-incentive/assets/67650132/3e8c937b-b74e-4db2-9f4d-22668f40c06f">

**Comment by PavelMakarchuk** [comment]
Also one other Column for the Delta in %

**Comment by PavelMakarchuk** [comment]
We also might add a header instead of the current output.

**Comment by emieelvire** [comment]
> We also might add a header instead of the current output.

What do we want the header to contain? Do we want to keep any of the current text in the header?

**Comment by PavelMakarchuk** [comment]
> > We also might add a header instead of the current output.
> 
> What do we want the header to contain? Do we want to keep any of the current text in the header?

You face a 'Bonus/Penalty' of x (y%).
