### ISSUE TITLE
Change the title color to while

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/us-marriage-incentive#53]
![image](https://github.com/PolicyEngine/us-marriage-incentive/assets/110687043/4f96a5d9-f0df-41ce-8920-eb3f856da313)

**Comment by PavelMakarchuk** [comment]
Currently black on black

**Comment by emieelvire** [comment]
<img width="708" alt="Screenshot 2024-04-11 at 9 35 53 AM" src="https://github.com/PolicyEngine/us-marriage-incentive/assets/67650132/d2fbe367-11d0-43a0-aaca-3e10342d396a">

This is how it appears on my screen currently after updating main. Is this still an issue?

**Comment by PavelMakarchuk** [comment]
> <img alt="Screenshot 2024-04-11 at 9 35 53 AM" width="708" src="https://private-user-images.githubusercontent.com/67650132/321712295-d2fbe367-11d0-43a0-aaca-3e10342d396a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTQ5NzIsIm5iZiI6MTcxMjg1NDY3MiwicGF0aCI6Ii82NzY1MDEzMi8zMjE3MTIyOTUtZDJmYmUzNjctMTFkMC00M2EwLWFhY2EtM2UxMDM0MmQzOTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE2NTc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NDEzNDIxMTExMzFiNmIwNTE2YmZiNTk4ZTA0MzNjNzI2YWNhNjIyOGM1ZjJlMmVjMzJiNmI4ZjJjYmQxNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._7_Mg4jRoKAbjfwvMinh6ngA5TtmrNMGmcL6xxkA_qM"> <img alt="Screenshot 2024-04-11 at 9 38 07 AM" width="783" src="https://private-user-images.githubusercontent.com/67650132/321712814-e71dff1c-ba58-44a2-8b37-855b83833df3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTQ5NzIsIm5iZiI6MTcxMjg1NDY3MiwicGF0aCI6Ii82NzY1MDEzMi8zMjE3MTI4MTQtZTcxZGZmMWMtYmE1OC00NGEyLThiMzctODU1YjgzODMzZGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE2NTc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyOGI3MjBjNzkxOGQ1NGZmMDVmMzQyYmUxOTlhNGVjODk4OGQzZmI1YzQwOWZmMzg4OTJlOTI2YWY2YjhjNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aJn3JCR0HF97wmf6yS6ilGNdR1nWJJ7nwn1OcQrJ1ro">
> This is how the titles appear on my screen currently after updating main. Is this still an issue?

Streamlit has an option to use dark mode, is it possible for us to adjust based on the switch?

**Comment by emieelvire** [comment]
<img width="917" alt="Screenshot 2024-05-02 at 10 57 35 AM" src="https://github.com/PolicyEngine/us-marriage-incentive/assets/67650132/ab592958-0acf-4be3-98f0-9cbc2aeeb33b">

**Comment by PavelMakarchuk** [comment]
Not needed
